// <auto-generated/>
using System;
using System.Globalization;
using System.Resources;
using System.Reflection;

namespace Tester
{
    internal static class Resources
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan is null)
                {
                    resourceMan = new ResourceManager("Tester.Resources", Assembly.GetExecutingAssembly());
                }
                return resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string MakingPrediction => ResourceManager.GetString("MakingPrediction", resourceCulture) ?? string.Empty;

        internal static string Top10FromPath => ResourceManager.GetString("Top10FromPath", resourceCulture) ?? string.Empty;

        internal static string MakingPredictionBytes => ResourceManager.GetString("MakingPredictionBytes", resourceCulture) ?? string.Empty;

        internal static string Top10FromBytes => ResourceManager.GetString("Top10FromBytes", resourceCulture) ?? string.Empty;
    }
}
