# For more info on HTTP files go to https://aka.ms/vs/httpfile
@HostDomain = https://localhost:5000

### Gets all the Reports
GET {{HostDomain}}/reports
Content-Type: application/json


### Creates and publish Report
POST {{HostDomain}}/reports

